 package teststructs

// This file is generated by the gen-merge package.
// Please avoid editing this manually.


func (s1 NullFloat) Merge(s2 NullFloat) NullFloat {
	
	if s1.Valid == *(new(bool)) {
		s1.Valid = s2.Valid
	}
	
	if s1.Float == *(new(float64)) {
		s1.Float = s2.Float
	}
	
	return s1
}

func (s1 Person) Merge(s2 Person) Person {
	
	if s1.Name == *(new(string)) {
		s1.Name = s2.Name
	}
	
	if s1.Age == *(new(int64)) {
		s1.Age = s2.Age
	}
	
	if s1.secretIdentity == *(new(string)) {
		s1.secretIdentity = s2.secretIdentity
	}
	
	if s1.favoriteCity == *(new(*string)) {
		s1.favoriteCity = s2.favoriteCity
	}
	
	if s1.Height == *(new(NullFloat)) {
		s1.Height = s2.Height
	}
	
	return s1
}

